### ISSUE TITLE
Speeding up 

### ISSUE THREAD

**Issue by rezpower** [ruinernin/foxystreams#19]
Hey ruinernin,
Thanks again for recent changes and updates. The addon is working great and almost perfect.
I only have a little suggestion to speed up browsing as everytime you go back in results foxystreams seem to be searching again. To explain what I mean: Imagine you search for keyword "rarbg"
Foxystreams will do a search and you get few results (with rarbg in filename). If you play one of the files to preview it and then click back to go to the search result (to check another file) foxystreams will redo it's search again. What if it would just go back to a cached result and stop re-searching everytime you hit the back button? If for any reason you want to refresh the search all you would need to do is to redo your search or have a refresh search option. (Which I doubt is needed).
Also many times when you go back it gives an error saying (No result found!) you then search again and it gives you results! 

PS btw is it possible to have file size show next to files? This would also be great! :)

**Comment by ruinernin** [comment]
>If you play one of the files to preview it and then click back to go to the search result (to check another file) foxystreams will redo it's search again

This should be handled by xbmc but I know the issue you are referencing. Thinking about it there are some workarounds, if it's a clean implementation it may be worth adding, in general [caching is avoided](https://martinfowler.com/bliki/TwoHardThings.html) in this addon.

> Also many times when you go back it gives an error saying (No result found!) you then search again and it gives you results!

That's because it gets back no results from the API, the exact reasons are unknown. Probably ratelimiting and/or caching server side.

>btw is it possible to have file size show next to files?

This should be do-able.
